file(READ "${SOURCE_ROOT}/src/CMakeLists.txt" SRC_CMAKE)
file(READ "${SOURCE_ROOT}/.github/workflows/core_linux_build.yml" LINUX_CI)
file(READ "${SOURCE_ROOT}/.github/workflows/core_windows_build.yml" WINDOWS_CI)

string(FIND "${SRC_CMAKE}" "Upstream realmd passes the *file*" POSITION)
if(NOT POSITION EQUAL -1)
  message(FATAL_ERROR "Obsolete external realmd VersionInfo workaround remains")
endif()

foreach(CI_TEXT IN ITEMS "${LINUX_CI}" "${WINDOWS_CI}")
  foreach(REQUIRED_TEXT "-DWITH_TESTS=1" "ctest --test-dir")
    string(FIND "${CI_TEXT}" "${REQUIRED_TEXT}" POSITION)
    if(POSITION EQUAL -1)
      message(FATAL_ERROR "CI does not run tests: ${REQUIRED_TEXT}")
    endif()
  endforeach()
endforeach()
