set(SRC_GRP_PROTO
    ClientConnection.cpp
    ClientConnection.h
    ConnectTo.cpp
    ConnectTo.h
    IClientLink.h
    IWorldGateway.h
    LinkSlot.h
    Listener.cpp
    Listener.h
    OpcodeSlots.cpp
    OpcodeSlots.h
    OpcodeSlots.inc
    Opcodes.h
    RedirectRegistry.cpp
    RedirectRegistry.h
    ServerRouting.cpp
    ServerRouting.h
    SessionLinks.cpp
    SessionLinks.h
    WorldPacket.h
    PacketCodec.cpp
    PacketCodec.h
    wire/MovementElements.h
    wire/MovementStatus.h
    wire/MovementCodec.h
    wire/MovementCodec.cpp
    wire/MovementSequences.h
    wire/MovementSequences.cpp
    wire/MovementParity.h
    wire/MovementParity.cpp
    wire/MovementLayouts.inc
    wire/gen_movement_layouts.py
    wire/MovementCapture.h
    wire/MovementCapture.cpp
    wire/ByteReader.h
    wire/GuidCodec.h
    wire/GuidCodec.cpp
    wire/KnockBackCodec.h
    wire/KnockBackCodec.cpp
    wire/MonsterMoveCodec.h
    wire/MonsterMoveCodec.cpp
    wire/MovementFamilies.h
    wire/MovementFamilies.cpp
    wire/MoverCodec.h
    wire/MoverCodec.cpp
    wire/TeleportCodec.h
    wire/TeleportCodec.cpp
)
source_group("proto" FILES ${SRC_GRP_PROTO})

add_library(proto STATIC ${SRC_GRP_PROTO})

target_include_directories(proto
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}
)

target_link_libraries(proto
    PUBLIC
        shared
        mangos_crypto
)
