if(CMAKE_CONFIGURATION_TYPES)
    string(REPLACE ";" "/" build_type "${CMAKE_CONFIGURATION_TYPES}")
    set(build_type "${build_type} (picked at build time)")
else()
    set(build_type "${CMAKE_BUILD_TYPE}")
endif()

if(WIN32)
    set(net_backend "IOCP")
elseif(MANGOS_USE_IO_URING)
    set(net_backend "io_uring")
elseif(APPLE OR CMAKE_SYSTEM_NAME MATCHES "BSD")
    set(net_backend "kqueue")
else()
    set(net_backend "epoll")
endif()

set(targets "")
if(BUILD_MANGOSD)
    list(APPEND targets "mangosd")
endif()
if(SCRIPT_LIB_SD3)
    list(APPEND targets "sd3")
endif()
if(BUILD_REALMD)
    list(APPEND targets "realmd")
endif()
if(BUILD_TOOLS)
    list(APPEND targets "tools")
endif()
if(WITH_TESTS OR WITH_NET_TESTS)
    list(APPEND targets "mangos_tests")
endif()
if(PCH)
    list(APPEND targets "pch")
endif()
string(REPLACE ";" " " targets "${targets}")

message("")
message("  ${MANGOS_PKG} ${PROJECT_VERSION}   ${rev_hash}  ${rev_date} (${rev_branch})")
message("  ----------------------------------------------------------------")
message("  Toolchain   ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}, C++${CMAKE_CXX_STANDARD}, ${CMAKE_HOST_SYSTEM}, cmake ${CMAKE_VERSION}")
message("  Build       ${build_type}, ${CMAKE_GENERATOR}, net ${net_backend}")
message("  Targets     ${targets}")
message("  Output      ${CMAKE_BINARY_DIR}")
message("  Install     ${BIN_DIR}  (configs: ${CONF_INSTALL_DIR})")
message("  ----------------------------------------------------------------")
message("  Client      build ${MANGOS_CLIENT_BUILD}, ${MANGOS_CLIENT_NAME}")
message("  Config      mangosd ${MANGOS_WORLD_VER}, realmd ${MANGOS_REALM_VER}, ahbot ${MANGOS_AHBOT_VER}")
message("  Database    world ${MANGOS_WORLD_DB_VERSION}.${MANGOS_WORLD_DB_STRUCTURE}.${MANGOS_WORLD_DB_CONTENT} (${MANGOS_WORLD_DB_DESCRIPT}), char ${MANGOS_CHAR_DB_VERSION}.${MANGOS_CHAR_DB_STRUCTURE}.${MANGOS_CHAR_DB_CONTENT}, realm ${MANGOS_REALMD_DB_VERSION}.${MANGOS_REALMD_DB_STRUCTURE}.${MANGOS_REALMD_DB_CONTENT}")

if(WITHOUT_GIT)
    message("")
    message("  WITHOUT_GIT: binaries will report \"unknown\" as their revision.")
endif()
if(WITH_NET_TESTS)
    message("")
    message("  WITH_NET_TESTS: the socket tests bind real ports and dominate the suite.")
endif()
message("")
